/**:
  ros__parameters: 
    platform_height: 2.0
    wheel_radius: 0.3
    wheel_length: 0.1
    wheel_mass: 0.5 # 2.0
    caster_radius: 0.1
    caster_length: 0.1
    caster_mass: 0.1 # 1.0
    # max_velocity: 3.0
    # gravity: 9.8
    body_x: 0.8
    body_y: 0.6 # 1.0 1.5
    body_z: 0.2
    body_mass: 2.0 # 10.0
