<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ddrive">

<xacro:property name="yaml_file" value="$(find diff_drive)/ddrive.yaml" />
<xacro:property name="props" value="${load_yaml(yaml_file)}" />
<xacro:property name="start"  value="${props['/**']}" />
<xacro:property name="ros__parameters"  value="${start['ros__parameters']}" />

<xacro:property name="platform_height"  value="${ros__parameters['platform_height']}" />

<xacro:property name="wheel_radius"  value="${ros__parameters['wheel_radius']}" />
<xacro:property name="wheel_length"  value="${ros__parameters['wheel_length']}" />
<xacro:property name="wheel_mass"  value="${ros__parameters['wheel_mass']}" />
<xacro:property name="caster_radius"  value="${ros__parameters['caster_radius']}" />
<xacro:property name="caster_length"  value="${ros__parameters['caster_length']}" />
<xacro:property name="caster_mass"  value="${ros__parameters['caster_mass']}" />
<xacro:property name="body_x"  value="${ros__parameters['body_x']}" />
<xacro:property name="body_y"  value="${ros__parameters['body_y']}" />
<xacro:property name="body_z"  value="${ros__parameters['body_z']}" />
<xacro:property name="body_mass"  value="${ros__parameters['body_mass']}" />


<xacro:property name="stem_lenght"  value="${platform_height-wheel_radius-wheel_radius-0.2-0.41-0.1}" />



<xacro:macro name="wheel_inertial" params="mass">
    <inertial>
            <mass value="${mass}" />
            <inertia ixx="1e-3" ixy="0.0" ixz="0.0"
                 iyy="1e-3" iyz="0.0"
                 izz="1e-3" />
    </inertial>
</xacro:macro>

<xacro:macro name="caster_inertial" params="mass">
    <inertial>
            <mass value="${mass}" />
            <inertia ixx="1e-3" ixy="0.0" ixz="0.0"
                 iyy="1e-3" iyz="0.0"
                 izz="1e-3" />
    </inertial>
</xacro:macro>


<xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
        <visual>
            <geometry>
                <cylinder length="0.1" radius="0.3"/>
            </geometry>
            <!-- <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/> -->
            <!-- <material name="white"/> -->
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
            <!-- <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/> -->
        </collision>
        <xacro:wheel_inertial mass="${wheel_mass}"/>
    </link>

    <joint name="base_link_to_${prefix}_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_wheel"/>
        <axis xyz="0 0 1"/>
        <origin rpy="0 1.57075 0" xyz="${reflect*(body_x/2 + wheel_length/2)} ${body_x/2} 0"/>
    </joint>
</xacro:macro>



<xacro:macro name="caster" params="prefix reflect">
    <link name="${prefix}_caster">
        <visual>
            <geometry>
                <cylinder length="0.1" radius="0.1"/>
            </geometry>
            <!-- <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/> -->
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <cylinder length="${caster_length}" radius="${caster_radius}"/>
            </geometry>
            <!-- <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/> -->
        </collision>
        <xacro:caster_inertial mass="${caster_mass}"/>
    </link>

    <joint name="base_link_to_${prefix}_caster" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_caster"/>
        <axis xyz="0 0 1"/>
        <origin rpy="0 1.57075 0" xyz="0 -${body_x/2 + caster_radius*2} ${reflect*(body_z/2 + caster_radius)}"/>
    </joint>

    <joint name="base_link_to_${prefix}_caster_turn" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_caster"/>
        <axis xyz="1 0 0"/>
        <origin rpy="0 1.57075 0" xyz="0 -${body_x/2 + caster_radius*2} ${reflect*(body_z/2 + caster_radius)}"/>
    </joint>
</xacro:macro>



  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_x} ${body_y} ${body_z}"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="${body_x} ${body_y} ${body_z}"/>
      </geometry>
    </collision>
    <xacro:caster_inertial mass="${body_mass}"/>
  </link>


<xacro:wheel prefix="right" reflect="1" />
<xacro:wheel prefix="left" reflect="-1" />

<xacro:caster prefix="top" reflect="1" />
<xacro:caster prefix="bottom" reflect="-1" />

</robot>
