<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ddrive">

<xacro:property name="yaml_file" value="$(find diff_drive)/ddrive.yaml" />
<xacro:property name="props" value="${load_yaml(yaml_file)}" />
<xacro:property name="start"  value="${props['/**']}" />
<xacro:property name="ros__parameters"  value="${start['ros__parameters']}" />
<xacro:property name="platform_height"  value="${ros__parameters['platform_height']}" />
<xacro:property name="wheel_radius"  value="${ros__parameters['wheel_radius']}" />
<xacro:property name="stem_lenght"  value="${platform_height-wheel_radius-wheel_radius-0.2-0.41-0.1}" />


<xacro:macro name="wheel" params="prefix reflect">
    <link name="${prefix}_wheel">
        <visual>
            <geometry>
                <cylinder length="0.1" radius="0.3"/>
            </geometry>
            <!-- <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/> -->
            <!-- <material name="white"/> -->
        </visual>
        <collision>
            <geometry>
                <cylinder length="0.1" radius="0.3"/>
            </geometry>
            <!-- <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/> -->
        </collision>
        <!-- <xacro:default_inertial mass="10"/> -->
    </link>

    <joint name="base_link_to_${prefix}_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_wheel"/>
        <axis xyz="0 0 1"/>
        <origin rpy="0 1.57075 0" xyz="${reflect*(0.8/2 + 0.1/2)} ${0.2/2 + stem_lenght/2} 0"/>
    </joint>
</xacro:macro>



<xacro:macro name="caster" params="prefix reflect">
    <link name="${prefix}_caster">
        <visual>
            <geometry>
                <cylinder length="0.1" radius="0.1"/>
            </geometry>
            <!-- <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/> -->
            <!-- <material name="white"/> -->
        </visual>
        <collision>
            <geometry>
                <cylinder length="0.1" radius="0.1"/>
            </geometry>
            <!-- <origin xyz="0 0 -${leglen/2}" rpy="0 ${pi/2} 0"/> -->
        </collision>
        <!-- <xacro:default_inertial mass="10"/> -->
    </link>

    <joint name="base_link_to_${prefix}_caster" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_caster"/>
        <axis xyz="0 0 1"/>
        <origin rpy="0 1.57075 0" xyz="0 -${0.2/2 + stem_lenght/2 + 0.1} ${reflect*(0.2/2 + 0.1)}"/>
    </joint>

    <joint name="base_link_to_${prefix}_caster_turn" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_caster"/>
        <axis xyz="1 0 0"/>
        <origin rpy="0 1.57075 0" xyz="0 -${0.2/2 + stem_lenght/2 + 0.1} ${reflect*(0.2/2 + 0.1)}"/>
    </joint>
</xacro:macro>



  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.8 1.5 0.2"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.8 1.5 0.2"/>
      </geometry>
    </collision>
  </link>


<xacro:wheel prefix="right" reflect="1" />
<xacro:wheel prefix="left" reflect="-1" />

<xacro:caster prefix="top" reflect="1" />
<xacro:caster prefix="bottom" reflect="-1" />

</robot>
