<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ddrive">

<xacro:property name="yaml_file" value="$(find diff_drive)/ddrive.yaml" />
<xacro:property name="props" value="${load_yaml(yaml_file)}" />
<xacro:property name="start"  value="${props['/**']}" />
<xacro:property name="ros__parameters"  value="${start['ros__parameters']}" />
<xacro:property name="platform_height"  value="${ros__parameters['platform_height']}" />
<xacro:property name="wheel_radius"  value="${ros__parameters['wheel_radius']}" />
<xacro:property name="stem_lenght"  value="${platform_height-wheel_radius-wheel_radius-0.2-0.41-0.1}" />




  <link name="Platform">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.4"/>
      </geometry>
      <origin rpy="0 0 1.57075" xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.4"/>
      </geometry>
      <origin rpy="0 0 1.57075" xyz="0 0 0"/>
    </collision>
  </link>

  <link name="Neck">
    <visual>
      <geometry>
        <cylinder length="0.41" radius="0.05"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.41" radius="0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="Neck_to_Platform" type="revolute">
    <parent link="Neck"/>
    <child link="Platform"/>
    <origin xyz="0 0 ${0.1/2 + 0.41/2}"/>
    <axis xyz="1 0 0"/>
    <limit effort="1000.0" lower="-1.1" upper="1.1" velocity="0.5"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.6 0.4 0.2"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.6 0.4 0.2"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_link_to_Neck" type="fixed">
    <parent link="base_link"/>
    <child link="Neck"/>
    <origin xyz="0 0 ${0.2/2 + 0.41/2}"/>
  </joint>

  <link name="stem">
    <visual>
      <geometry>
        <cylinder length="${stem_lenght}" radius="0.1"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${stem_lenght}" radius="0.1"/>
      </geometry>
    </collision>
  </link>

  <joint name="base_link_to_stem" type="continuous">
    <parent link="base_link"/>
    <child link="stem"/>
    <axis xyz="0 0 -1"/>
    <origin xyz="0 0 -${0.2/2 + stem_lenght/2}"/>
  </joint>

  <link name="wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 0"/>
    </collision>
  </link>

  <joint name="stem_to_wheel" type="continuous">
    <parent link="stem"/>
    <child link="wheel"/>
    <axis xyz="1 0 0"/>
    <origin xyz="0 0 -${wheel_radius + (stem_lenght/2)}"/>
  </joint>

</robot>
