<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="ddrive">

<xacro:property name="yaml_file" value="$(find diff_drive)/ddrive.yaml" />
<xacro:property name="props" value="${load_yaml(yaml_file)}" />
<xacro:property name="start"  value="${props['/**']}" />
<xacro:property name="ros__parameters"  value="${start['ros__parameters']}" />

<xacro:property name="platform_height"  value="${ros__parameters['platform_height']}" />

<xacro:property name="wheel_radius"  value="${ros__parameters['wheel_radius']}" />
<xacro:property name="wheel_length"  value="${ros__parameters['wheel_length']}" />
<xacro:property name="wheel_mass"  value="${ros__parameters['wheel_mass']}" />
<xacro:property name="caster_radius"  value="${ros__parameters['caster_radius']}" />
<xacro:property name="caster_mass"  value="${ros__parameters['caster_mass']}" />
<xacro:property name="body_x"  value="${ros__parameters['body_x']}" />
<xacro:property name="body_y"  value="${ros__parameters['body_y']}" />
<xacro:property name="body_z"  value="${ros__parameters['body_z']}" />
<xacro:property name="body_mass"  value="${ros__parameters['body_mass']}" />


<xacro:include filename="$(find diff_drive)/ddrive.gazebo.xacro" />

<material name = "red">
    <color rgba ="1 0 0 1" />
</material>

<material name = "blue">
    <color rgba ="0 0 1 1" />
</material>

<material name = "green">
    <color rgba ="0 1 0 1" />
</material>



<xacro:macro name="wheel_inertial" params="mass">
    <inertial>
            <mass value="${mass}" />
            <inertia ixx="${mass*(3*wheel_radius**2 + wheel_length**2)/12}" ixy="0.0" ixz="0.0"
                 iyy="${mass*(3*wheel_radius**2 + wheel_length**2)/12}" iyz="0.0"
                 izz="${mass*(wheel_radius**2)/2}" />
    </inertial>
</xacro:macro>

<xacro:macro name="caster_inertial" params="mass">
    <inertial>
            <mass value="${mass}" />
            <inertia ixx="${mass*(caster_radius**2 + caster_radius**2)/5}" ixy="0.0" ixz="0.0"
                 iyy="${mass*(caster_radius**2 + caster_radius**2)/5}" iyz="0.0"
                 izz="${mass*(caster_radius**2 + caster_radius**2)/5}"/>
    </inertial>
</xacro:macro>

<xacro:macro name="body_inertial" params="mass">
    <inertial>
            <mass value="${mass}" />
            <inertia ixx="${mass*(body_y**2 + body_z**2)/12}" ixy="0.0" ixz="0.0"
                 iyy="${mass*(body_x**2 + body_z**2)/12}" iyz="0.0"
                 izz="${mass*(body_x**2 + body_y**2)/12}" />
    </inertial>
</xacro:macro>


<xacro:macro name="wheel" params="prefix reflect color">
    <link name="${prefix}_wheel">
        <visual>
            <geometry>
                <cylinder length="0.1" radius="0.3"/>
            </geometry>
            <material name = "${color}" />
        </visual>
        <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:wheel_inertial mass="${wheel_mass}"/>
    </link>

    <joint name="base_link_to_${prefix}_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_wheel"/>
        <axis xyz="0 0 1"/>
        <origin rpy="1.57075 1.57075 0" xyz="${body_x/2 - 0.2} ${reflect*(body_x/2 + wheel_length/2)} 0"/>
    </joint>
</xacro:macro>



<xacro:macro name="caster" params="prefix reflect color">
    <link name="${prefix}_caster">
        <visual>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
            <material name = "${color}" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_radius}"/>
            </geometry>
        </collision>
        <xacro:caster_inertial mass="${caster_mass}"/>
    </link>

    <joint name="base_link_to_${prefix}_caster" type="continuous">
        <parent link="base_link"/>
        <child link="${prefix}_caster"/>
        <axis xyz="0 0 1"/>
        <origin rpy="0 1.57075 1.57075" xyz="-${body_x/2 - 0.1} 0 ${reflect*(body_z/2 + caster_radius)}"/>
    </joint>
</xacro:macro>



  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_x} ${body_y} ${body_z}"/>
      </geometry>
      <material name = "red" />
       <origin rpy="0 0 1.57075" xyz="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_x} ${body_y} ${body_z}"/>
      </geometry>
      <origin rpy="0 0 1.57075" xyz="0 0 0"/>
    </collision>
    <xacro:body_inertial mass="${body_mass}"/>
  </link>


<xacro:wheel prefix="right" reflect="1" color ="blue"/>
<xacro:wheel prefix="left" reflect="-1" color ="blue"/>

<xacro:caster prefix="top" reflect="1" color ="green"/>
<xacro:caster prefix="bottom" reflect="-1" color ="green"/>

</robot>
